In [1]:
from IPython import display
import numpy as np
import random
import torch

In [ ]:
# 1. Создайте случайный FloatTensor размера 3x4x5

In [33]:
b = torch.randn(3, 4, 5).type(torch.FloatTensor)
b

tensor([[[-1.8746, -0.6120,  0.5565, -0.2019, -0.4360],
         [-0.4404,  0.8994,  1.6982, -0.5157, -0.5647],
         [-0.1462,  1.5080, -1.3776, -0.1607,  0.8001],
         [ 1.0832, -0.4813, -0.7962, -1.3673,  0.1854]],

        [[-0.2974, -0.8391,  0.1897, -1.9949,  1.1139],
         [ 0.1279, -0.0523, -2.1656, -1.3535, -0.0030],
         [ 1.2434, -1.6654,  2.0018, -0.4685, -0.9994],
         [ 0.6983, -0.2532, -0.6050,  1.1769, -0.1589]],

        [[ 1.3729, -1.1770, -0.0896,  0.3982,  1.6095],
         [-0.7738, -0.7879, -0.4948,  0.7702, -0.3111],
         [-1.1654, -0.5321,  0.1229, -0.0495, -0.3366],
         [-0.1045,  0.6379, -0.6465, -1.9448,  0.7145]]])

In [34]:
# 2. Выведите его форму (shape)

In [35]:
b.shape

torch.Size([3, 4, 5])

In [36]:
# 3. Приведите его к форме 6х10

In [47]:
print(f"Reshape: \n{b.reshape(6, 10)} \nshape: {b.reshape(6, 10).size()}")

Reshape: 
tensor([[-1.8746, -0.6120,  0.5565, -0.2019, -0.4360, -0.4404,  0.8994,  1.6982,
         -0.5157, -0.5647],
        [-0.1462,  1.5080, -1.3776, -0.1607,  0.8001,  1.0832, -0.4813, -0.7962,
         -1.3673,  0.1854],
        [-0.2974, -0.8391,  0.1897, -1.9949,  1.1139,  0.1279, -0.0523, -2.1656,
         -1.3535, -0.0030],
        [ 1.2434, -1.6654,  2.0018, -0.4685, -0.9994,  0.6983, -0.2532, -0.6050,
          1.1769, -0.1589],
        [ 1.3729, -1.1770, -0.0896,  0.3982,  1.6095, -0.7738, -0.7879, -0.4948,
          0.7702, -0.3111],
        [-1.1654, -0.5321,  0.1229, -0.0495, -0.3366, -0.1045,  0.6379, -0.6465,
         -1.9448,  0.7145]]) 
shape: torch.Size([6, 10])


In [38]:
# 4. Создайте случайный IntTensor размера 10

In [39]:
a = torch.randn(10).type(torch.IntTensor)
a

tensor([ 0,  0, -1,  0,  0, -1, -1,  1, -2, -2], dtype=torch.int32)

In [40]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [55]:
b * a

tensor([[-0.0000, -0.0000, -0.5565, -0.0000, -0.0000,  0.4404, -0.8994,  1.6982,
          1.0314,  1.1294],
        [-0.0000,  0.0000,  1.3776, -0.0000,  0.0000, -1.0832,  0.4813, -0.7962,
          2.7346, -0.3708],
        [-0.0000, -0.0000, -0.1897, -0.0000,  0.0000, -0.1279,  0.0523, -2.1656,
          2.7071,  0.0061],
        [ 0.0000, -0.0000, -2.0018, -0.0000, -0.0000, -0.6983,  0.2532, -0.6050,
         -2.3539,  0.3178],
        [ 0.0000, -0.0000,  0.0896,  0.0000,  0.0000,  0.7738,  0.7879, -0.4948,
         -1.5405,  0.6223],
        [-0.0000, -0.0000, -0.1229, -0.0000, -0.0000,  0.1045, -0.6379, -0.6465,
          3.8895, -1.4290]])

In [ ]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

In [64]:
b = b[:, :6] * (b[:, :6])
print(b)
print(b.shape)

tensor([[3.5142e+00, 3.7449e-01, 3.0971e-01, 4.0762e-02, 1.9006e-01, 1.9396e-01],
        [2.1387e-02, 2.2742e+00, 1.8977e+00, 2.5809e-02, 6.4022e-01, 1.1734e+00],
        [8.8441e-02, 7.0401e-01, 3.5999e-02, 3.9796e+00, 1.2409e+00, 1.6349e-02],
        [1.5461e+00, 2.7735e+00, 4.0073e+00, 2.1950e-01, 9.9875e-01, 4.8766e-01],
        [1.8848e+00, 1.3853e+00, 8.0353e-03, 1.5860e-01, 2.5906e+00, 5.9871e-01],
        [1.3583e+00, 2.8310e-01, 1.5103e-02, 2.4536e-03, 1.1329e-01, 1.0920e-02]])
torch.Size([6, 6])


In [ ]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [80]:
u = torch.tensor([1, 0.5, 2], requires_grad=True)
y = u**3 + u - 75*u
y.backward(u)
print(u.grad)

tensor([ -71.0000,  -36.6250, -124.0000])


In [ ]:
# 8. Создайте единичный тензор размера 5x6

In [70]:
c = torch.zeros((5, 6))
c

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [ ]:
# 9. Переведите его в формат numpy

In [71]:
c = c.numpy()

In [74]:
c

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)